### ISSUE TITLE
Cannot import name '_wrap_std_stream' from 'asyncclick._winconsole'

### ISSUE THREAD

**Issue by 0Kit** [0Kit/aiogram_template#1]
Found a problem in [asyncclick ](https://pypi.org/project/asyncclick/) related to the use of [wsl2](https://docs.microsoft.com/en-us/windows/wsl/install-win10). I don't know how to fix it yet. However, if you use wsl2 to call the file `init_db.py`, it works without errors

Error looks like:
`Traceback (most recent call last):`
`..File "init_db.py", line 1, in <module>`
`....import asyncclick as click`
`..File "D:\projdir\venv\lib\site-packages\asyncclick\__init__.py", line 7, in <module>`
`....from .core import Argument`
`..File "D:\projdir\venv\lib\site-packages\asyncclick\core.py", line 18, in <module>`
`....from ._compat import isidentifier`
`..File "D:\projdir\venv\lib\site-packages\asyncclick\_compat.py", line 540, in <module>`
`....from ._winconsole import _get_windows_console_stream, _wrap_std_stream`
`ImportError: cannot import name '_wrap_std_stream' from 'asyncclick._winconsole' (D:projdir\venv\lib\site-packages\asyncclick\_winconsole.py)`

**Comment by 0Kit** [comment]
**_Fixed_**
[Commit](https://github.com/0Kit/aiogram_template/commit/1c65d6fe2eb18d4d7b0082e05801b5bb17aa21b5) 18.10.2020
